### PR TITLE
Refactor action workflows

### PR DESCRIPTION
**Pull request by ztroop**
To summarize what I'm proposing ... We currently have 3 workflows:

- A workflow to trigger for dev.
- A workflow to trigger for master.
- A workflow to trigger an ISO release for master.

However, all three workflows are activated with `push` and `pull_request` events. I don't think this is intended behaviour. Any pull request that is made against `dev` will trigger the `pull_request` event. The `push` event here is redundant. As I mentioned before, we can optimize things further by excluding paths that don't affect the creation of the ISO.

I think I understand the intent behind `master-build.yml` and `release.yml`. You want to test the creation of the ISO and release it. However, both are triggered for `push` and `pull_request` events, which isn't needed. If we determine `dev` is ready for a release ... I'm assuming you would create a PR from `dev` to `master`. Creating the PR will trigger the `pull_request` event for the `master-build.yml`. If the test passes, reviewers accept, merge the PR. When merged, the `push` event in `release.yml` would officially release the ISO.

We can shorten this into two  files.

### CODE REVIEW

**Comment by 5nacks** [comment]
@xFreed0m do you have time to review?

**Comment by phunkpwnz** [comment]
Any reason the comments explaining some of the actions are being removed ?

**Comment by ztroop** [comment]
> Any reason the comments explaining some of the actions are being removed ?

This is an opinionated answer, but workflow configuration should be succinct. Comments are great for providing context and answering the `why` behind the code. If the line can be explained by reading official documentation, it's only bloating the configuration details. In contrast, _if there was a questionable override, or some other setting (because the absence of it would result in some obscure error)_, the comment provide more value.

As I said, this is strictly an opinion. I have Clean Code's Robert Martin (Uncle Bob) screaming in my ear. :laughing: I can re-add the comments if there are strong feelings about this.

**Comment by phunkpwnz** [comment]
Agreed, but I think the comments serve two purposes. The inline comments help with the abstraction from the github actions variable reference and the additional flow comments help for users not familiar with Github actions in general. They don't seem too verbose nor cluttered. But like you said this is just a matter of opinions

**Comment by xFreed0m** [comment]
The current Actions were built to cover the common use cases we have:

- We want to make sure the iso is able to be built properly for every push of code or PR - most of it happens on dev (that's why dev have a different action - it needs to take the dev branch code, and master is using master code when we make changes to that branch - it allows us to identify if a change breaks a build
- the reason we are using both push and pull, is that if someone pushes code directly to the branch, and if someone open a PR to a monitored branch.
- Regarding the comments - At least IMO,  I'm not a developer or a GitHub expert - comments makes everything clearer for the rest so it easier for us to help each other.

Last, I'm not clear what problem we are trying to fix in this PR (specially since the builds are failing lol)

**Comment by ztroop** [comment]
> the reason we are using both push and pull, is that if someone pushes code directly to the branch, and if someone open a PR to a monitored branch.

Ah! Then this workflow makes more sense. I was operating on the assumption that contributing pull requests would be merged into `dev`, then "finalized" into a release when `dev` is merged into `master`. If we have folks directly pushing to these branches, that conflicts with workflow in my mind.

> Last, I'm not clear what problem we are trying to fix in this PR (specially since the builds are failing lol)

This wasn't aiming to solve any particular problem and is unrelated to the disk space issue we're currently running into with the GitHub runner. It was only an attempt to optimize the action workflows.

**Comment by xFreed0m** [comment]
Oh ok, I was certain I've missed something.
I'm connecting with you in Slack to align for the next steps then?

**Review by 5nacks — APPROVED** [review]
approved

**Comment by ztroop** [comment]
I plan on doing a video demonstration on an automated build and deployment pipeline. It will simplify a lot of the sentiments discussed in this pull request. For now I'll close this, and I'll share more details in Slack in the near future.

**Pull request closed without merging**
